apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-cont-1-pvc

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: africa
  resources:
    requests:
      storage: 64Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-cont-1

  labels:
    app: win-cont-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win-cont-1
  template:
    metadata:
      labels:
        app: win-cont-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-dev3
      containers:
        - name: windows
          image: dockurr/windows
          env:
            - name: VERSION
              value: "11"
            - name: DISK_SIZE
              value: "64G"
          ports:
            - containerPort: 8006
              name: http
              protocol: TCP
            - containerPort: 3389
              name: rdp
              protocol: TCP
            - containerPort: 3389
              name: udp
              protocol: UDP
            - containerPort: 5900
              name: vnc
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          volumeMounts:
            - mountPath: /storage
              name: win-storage
            - mountPath: /dev/kvm
              name: dev-kvm
            - mountPath: /dev/net/tun
              name: dev-tun
      volumes:
        - name: win-storage
          persistentVolumeClaim:
            claimName: win-cont-1-pvc
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: win-cont-1

spec:
  type: LoadBalancer
  loadBalancerIP: 20.95.5.28
  selector:
    app: win-cont-1
  ports:
    - name: http
      port: 8006
      targetPort: 8006
      protocol: TCP
    - name: rdp
      port: 3389
      targetPort: 3389
      protocol: TCP
    - name: udp
      port: 3389
      targetPort: 3389
      protocol: UDP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
