---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudflared
spec:
  serviceName: cloudflared
  replicas: 3
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cloudflared
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: ["cloudflared", "tunnel", "--no-autoupdate", "run", "--token", "eyJhIjoiMmU4NjEzYzhlMWQ3MWQ2YTg2NjhlOTJkMTJmN2QwNWUiLCJ0IjoiNDk0ZTliMDAtOTMzYS00ZjJiLWE5ZmMtMTg2ZjFhNGQyNWFlIiwicyI6Ik4yUXpabUprTWpZdE1qVTBNeTAwT1RkaExUa3lNbUl0WXpJNVptTXlaRFZoT0RKaiJ9"]
          volumeMounts:
            - name: cft-data
              mountPath: /mnt/cft
  volumeClaimTemplates:
    - metadata:
        name: cft-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: europe
